#!/bin/sh
cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export LANG=zh_CN.UTF-8
export GLFW_IM_MODULE=ibus
export QT_STYLE_OVERRIDE=kvantum
export http_proxy=http://127.0.0.1:7890
export https_proxy=http://127.0.0.1:7890
export INPUT_METHOD=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"
export SDL_IM_MODULE=fcitx
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct
Hyprland
